//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.594.0 using the following command:
// XmlSchemaClassGenerator.Console -o . -n http://graphml.graphdrawing.org/xmlns=GraphML -n http://www.w3.org/1999/xlink=XLink --nu --sf --csm=Public --ct=System.Array --dc .\_XSD\graphml_complete.xsd
namespace GraphML
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.594.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("graph.edgedefault.type", Namespace="http://graphml.graphdrawing.org/xmlns")]
    public enum GraphPeriodEdgedefaultPeriodType
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("directed")]
        Directed,
        
        [System.Xml.Serialization.XmlEnumAttribute("undirected")]
        Undirected,
    }
}
