//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 1.0.0.0 using the following command:
// XmlSchemaClassGenerator.Console -o . -n http://graphml.graphdrawing.org/xmlns=GraphML -n http://www.w3.org/1999/xlink=XLink --nu --sf --pascal --csm=Public --ct=System.Array --dc .\_XSD\graphml_complete.xsd
namespace GraphML
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("graph.type", Namespace="http://graphml.graphdrawing.org/xmlns")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("graph", Namespace="http://graphml.graphdrawing.org/xmlns")]
    public partial class GraphType : IGraphExtraAttrib
    {
        
        [System.Xml.Serialization.XmlElementAttribute("desc")]
        public string Desc { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private DataType[] data;
        
        [System.Xml.Serialization.XmlElementAttribute("data")]
        public DataType[] Data
        {
            get
            {
                return this.data;
            }
            set
            {
                this.data = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DataSpecified
        {
            get
            {
                return ((this.Data != null) 
                            && (this.Data.Length != 0));
            }
        }
        
        public GraphType()
        {
            this.data = System.Array.Empty<DataType>();
            this.node = System.Array.Empty<NodeType>();
            this.edge = System.Array.Empty<EdgeType>();
            this.hyperedge = System.Array.Empty<HyperedgeType>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private NodeType[] node;
        
        [System.Xml.Serialization.XmlElementAttribute("node")]
        public NodeType[] Node
        {
            get
            {
                return this.node;
            }
            set
            {
                this.node = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NodeSpecified
        {
            get
            {
                return ((this.Node != null) 
                            && (this.Node.Length != 0));
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private EdgeType[] edge;
        
        [System.Xml.Serialization.XmlElementAttribute("edge")]
        public EdgeType[] Edge
        {
            get
            {
                return this.edge;
            }
            set
            {
                this.edge = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EdgeSpecified
        {
            get
            {
                return ((this.Edge != null) 
                            && (this.Edge.Length != 0));
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private HyperedgeType[] hyperedge;
        
        [System.Xml.Serialization.XmlElementAttribute("hyperedge")]
        public HyperedgeType[] Hyperedge
        {
            get
            {
                return this.hyperedge;
            }
            set
            {
                this.hyperedge = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HyperedgeSpecified
        {
            get
            {
                return ((this.Hyperedge != null) 
                            && (this.Hyperedge.Length != 0));
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("locator")]
        public LocatorType Locator { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("attr.name")]
        public string AttrName { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("attr.type")]
        public KeyTypeType AttrType { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AttrTypeSpecified { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("id")]
        public string Id { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("edgedefault")]
        public GraphEdgedefaultType Edgedefault { get; set; }
    }
}
