//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 1.0.0.0 using the following command:
// XmlSchemaClassGenerator.Console -o . -n http://graphml.graphdrawing.org/xmlns=GraphML -n http://www.w3.org/1999/xlink=XLink --nu --sf --pascal --csm=Public --ct=System.Array --dc .\_XSD\graphml_complete.xsd
namespace GraphML
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("graphml.type", Namespace="http://graphml.graphdrawing.org/xmlns")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("graphml", Namespace="http://graphml.graphdrawing.org/xmlns")]
    public partial class GraphMLType : IGraphmlExtraAttrib
    {
        
        [System.Xml.Serialization.XmlElementAttribute("desc")]
        public string Desc { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private KeyType[] key;
        
        [System.Xml.Serialization.XmlElementAttribute("key")]
        public KeyType[] Key
        {
            get
            {
                return this.key;
            }
            set
            {
                this.key = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool KeySpecified
        {
            get
            {
                return ((this.Key != null) 
                            && (this.Key.Length != 0));
            }
        }
        
        public GraphMLType()
        {
            this.key = System.Array.Empty<KeyType>();
            this.graph = System.Array.Empty<GraphType>();
            this.data = System.Array.Empty<DataType>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private GraphType[] graph;
        
        [System.Xml.Serialization.XmlElementAttribute("graph")]
        public GraphType[] Graph
        {
            get
            {
                return this.graph;
            }
            set
            {
                this.graph = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GraphSpecified
        {
            get
            {
                return ((this.Graph != null) 
                            && (this.Graph.Length != 0));
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private DataType[] data;
        
        [System.Xml.Serialization.XmlElementAttribute("data")]
        public DataType[] Data
        {
            get
            {
                return this.data;
            }
            set
            {
                this.data = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DataSpecified
        {
            get
            {
                return ((this.Data != null) 
                            && (this.Data.Length != 0));
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute("attr.name")]
        public string AttrName { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("attr.type")]
        public KeyTypeType AttrType { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AttrTypeSpecified { get; set; }
    }
}
