//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.594.0 using the following command:
// XmlSchemaClassGenerator.Console -o . -n http://graphml.graphdrawing.org/xmlns=GraphML -n http://www.w3.org/1999/xlink=XLink --nu --sf --csm=Public --ct=System.Array --dc .\_XSD\graphml_complete.xsd
namespace GraphML
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.594.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("key.for.type", Namespace="http://graphml.graphdrawing.org/xmlns")]
    public enum KeyPeriodForPeriodType
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("all")]
        All,
        
        [System.Xml.Serialization.XmlEnumAttribute("graphml")]
        Graphml,
        
        [System.Xml.Serialization.XmlEnumAttribute("graph")]
        Graph,
        
        [System.Xml.Serialization.XmlEnumAttribute("node")]
        Node,
        
        [System.Xml.Serialization.XmlEnumAttribute("edge")]
        Edge,
        
        [System.Xml.Serialization.XmlEnumAttribute("hyperedge")]
        Hyperedge,
        
        [System.Xml.Serialization.XmlEnumAttribute("port")]
        Port,
        
        [System.Xml.Serialization.XmlEnumAttribute("endpoint")]
        Endpoint,
    }
}
