//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 1.0.0.0 using the following command:
// XmlSchemaClassGenerator.Console -o . -n http://graphml.graphdrawing.org/xmlns=GraphML -n http://www.w3.org/1999/xlink=XLink -n http://www.yworks.com/xml/graphml=YEd --nu --sf --csm=Public --ct=System.Array --dc .\_XSD\ygraphml.xsd
namespace YEd
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("arrowType.type", Namespace="http://www.yworks.com/xml/graphml")]
    public enum ArrowTypeType
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("standard")]
        Standard,
        
        [System.Xml.Serialization.XmlEnumAttribute("delta")]
        Delta,
        
        [System.Xml.Serialization.XmlEnumAttribute("diamond")]
        Diamond,
        
        [System.Xml.Serialization.XmlEnumAttribute("white_diamond")]
        White_Diamond,
        
        [System.Xml.Serialization.XmlEnumAttribute("white_delta")]
        White_Delta,
        
        [System.Xml.Serialization.XmlEnumAttribute("none")]
        None,
        
        [System.Xml.Serialization.XmlEnumAttribute("plain")]
        Plain,
        
        [System.Xml.Serialization.XmlEnumAttribute("concave")]
        Concave,
        
        [System.Xml.Serialization.XmlEnumAttribute("convex")]
        Convex,
        
        [System.Xml.Serialization.XmlEnumAttribute("circle")]
        Circle,
        
        [System.Xml.Serialization.XmlEnumAttribute("dash")]
        Dash,
        
        [System.Xml.Serialization.XmlEnumAttribute("transparent_circle")]
        Transparent_Circle,
        
        [System.Xml.Serialization.XmlEnumAttribute("skewed_dash")]
        Skewed_Dash,
        
        [System.Xml.Serialization.XmlEnumAttribute("t_shape")]
        T_Shape,
    }
}
