//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 1.0.0.0 using the following command:
// XmlSchemaClassGenerator.Console -o . -n http://graphml.graphdrawing.org/xmlns=GraphML -n http://www.w3.org/1999/xlink=XLink -n http://www.yworks.com/xml/graphml=YEd --nu --sf --csm=Public --ct=System.Array --dc .\_XSD\ygraphml.xsd
namespace YEd
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("DropShadow.type", Namespace="http://www.yworks.com/xml/graphml")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DropShadowType
    {
        
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("#(([A-F]|[0-9]){2}){3,4}")]
        [System.Xml.Serialization.XmlAttributeAttribute("color")]
        public string Color { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("offsetX")]
        public sbyte OffsetX { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OffsetXSpecified { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("offsetY")]
        public sbyte OffsetY { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OffsetYSpecified { get; set; }
    }
}
