//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 1.0.0.0 using the following command:
// XmlSchemaClassGenerator.Console -o . -n http://graphml.graphdrawing.org/xmlns=GraphML -n http://www.w3.org/1999/xlink=XLink -n http://www.yworks.com/xml/graphml=YEd --nu --sf --csm=Public --ct=System.Array --dc .\_XSD\ygraphml.xsd
namespace YEd
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("edgeLabelPosition.type", Namespace="http://www.yworks.com/xml/graphml")]
    public enum EdgeLabelPositionType
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("center")]
        Center,
        
        [System.Xml.Serialization.XmlEnumAttribute("tcentr")]
        Tcentr,
        
        [System.Xml.Serialization.XmlEnumAttribute("scentr")]
        Scentr,
        
        [System.Xml.Serialization.XmlEnumAttribute("anywhere")]
        Anywhere,
        
        [System.Xml.Serialization.XmlEnumAttribute("stail")]
        Stail,
        
        [System.Xml.Serialization.XmlEnumAttribute("ttail")]
        Ttail,
        
        [System.Xml.Serialization.XmlEnumAttribute("tail")]
        Tail,
        
        [System.Xml.Serialization.XmlEnumAttribute("shead")]
        Shead,
        
        [System.Xml.Serialization.XmlEnumAttribute("thead")]
        Thead,
        
        [System.Xml.Serialization.XmlEnumAttribute("head")]
        Head,
    }
}
