//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 1.0.0.0 using the following command:
// XmlSchemaClassGenerator.Console -o . -n http://graphml.graphdrawing.org/xmlns=GraphML -n http://www.w3.org/1999/xlink=XLink -n http://www.yworks.com/xml/graphml=YEd --nu --sf --csm=Public --ct=System.Array --dc .\_XSD\ygraphml.xsd
namespace YEd
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("edgeLabelModel.type", Namespace="http://www.yworks.com/xml/graphml")]
    public enum EdgeLabelModelType
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("centered")]
        Centered,
        
        [System.Xml.Serialization.XmlEnumAttribute("center_slider")]
        Center_Slider,
        
        [System.Xml.Serialization.XmlEnumAttribute("side_slider")]
        Side_Slider,
        
        [System.Xml.Serialization.XmlEnumAttribute("free")]
        Free,
        
        [System.Xml.Serialization.XmlEnumAttribute("two_pos")]
        Two_Pos,
        
        [System.Xml.Serialization.XmlEnumAttribute("three_center")]
        Three_Center,
        
        [System.Xml.Serialization.XmlEnumAttribute("six_pos")]
        Six_Pos,
        
        [System.Xml.Serialization.XmlEnumAttribute("custom")]
        Custom,
    }
}
