//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 1.0.0.0 using the following command:
// XmlSchemaClassGenerator.Console -o . -n http://graphml.graphdrawing.org/xmlns=GraphML -n http://www.w3.org/1999/xlink=XLink -n http://www.yworks.com/xml/graphml=YEd --nu --sf --csm=Public --ct=System.Array --dc .\_XSD\ygraphml.xsd
namespace YEd
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("Insets.type", Namespace="http://www.yworks.com/xml/graphml")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsetsType : IntInsetsType
    {
        
        [System.Xml.Serialization.XmlAttributeAttribute("topF")]
        public double TopF { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TopFSpecified { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("bottomF")]
        public double BottomF { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BottomFSpecified { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("leftF")]
        public double LeftF { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LeftFSpecified { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("rightF")]
        public double RightF { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RightFSpecified { get; set; }
    }
}
