//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 1.0.0.0 using the following command:
// XmlSchemaClassGenerator.Console -o . -n http://graphml.graphdrawing.org/xmlns=GraphML -n http://www.w3.org/1999/xlink=XLink -n http://www.yworks.com/xml/graphml=YEd --nu --sf --csm=Public --ct=System.Array --dc .\_XSD\ygraphml.xsd
namespace YEd
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("PortLabelModel.type", Namespace="http://www.yworks.com/xml/graphml")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("PortLabelModel", Namespace="http://www.yworks.com/xml/graphml")]
    public partial class PortLabelModelType
    {
        
        [System.Xml.Serialization.XmlAttributeAttribute("localCandidatesEnabled")]
        public bool LocalCandidatesEnabled { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LocalCandidatesEnabledSpecified { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("offset")]
        public double Offset { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OffsetSpecified { get; set; }
    }
}
