//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 1.0.0.0 using the following command:
// XmlSchemaClassGenerator.Console -o . -n http://graphml.graphdrawing.org/xmlns=GraphML -n http://www.w3.org/1999/xlink=XLink -n http://www.yworks.com/xml/graphml=YEd --nu --sf --csm=Public --ct=System.Array --dc .\_XSD\ygraphml.xsd
namespace YEd
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("shapeType.type", Namespace="http://www.yworks.com/xml/graphml")]
    public enum ShapeTypeType
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("rectangle")]
        Rectangle,
        
        [System.Xml.Serialization.XmlEnumAttribute("roundrectangle")]
        Roundrectangle,
        
        [System.Xml.Serialization.XmlEnumAttribute("ellipse")]
        Ellipse,
        
        [System.Xml.Serialization.XmlEnumAttribute("parallelogram")]
        Parallelogram,
        
        [System.Xml.Serialization.XmlEnumAttribute("hexagon")]
        Hexagon,
        
        [System.Xml.Serialization.XmlEnumAttribute("octagon")]
        Octagon,
        
        [System.Xml.Serialization.XmlEnumAttribute("diamond")]
        Diamond,
        
        [System.Xml.Serialization.XmlEnumAttribute("triangle")]
        Triangle,
        
        [System.Xml.Serialization.XmlEnumAttribute("trapezoid")]
        Trapezoid,
        
        [System.Xml.Serialization.XmlEnumAttribute("trapezoid2")]
        Trapezoid2,
        
        [System.Xml.Serialization.XmlEnumAttribute("rectangle3d")]
        Rectangle3D,
    }
}
