//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 1.0.0.0 using the following command:
// XmlSchemaClassGenerator.Console -o . -n http://graphml.graphdrawing.org/xmlns=GraphML -n http://www.w3.org/1999/xlink=XLink -n http://www.yworks.com/xml/graphml=YEd --nu --sf --csm=Public --ct=System.Array --dc .\_XSD\ygraphml.xsd
namespace YEd
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("SimpleStyle", Namespace="http://www.yworks.com/xml/graphml", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("SimpleStyle", Namespace="http://www.yworks.com/xml/graphml")]
    public partial class SimpleStyle
    {
        
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("#(([A-F]|[0-9]){2}){3,4}")]
        [System.Xml.Serialization.XmlAttributeAttribute("fillColor")]
        public string FillColor { get; set; }
        
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("#(([A-F]|[0-9]){2}){3,4}")]
        [System.Xml.Serialization.XmlAttributeAttribute("lineColor")]
        public string LineColor { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("lineType")]
        public LineTypeType LineType { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LineTypeSpecified { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("lineWidth")]
        public double LineWidth { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LineWidthSpecified { get; set; }
    }
}
