//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 1.0.0.0 using the following command:
// XmlSchemaClassGenerator.Console -o . -n http://graphml.graphdrawing.org/xmlns=GraphML -n http://www.w3.org/1999/xlink=XLink --nu --sf --csm=Public --ct=System.Array --dc .\_XSD\graphml_complete.xsd
namespace GraphML
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("graph.order.type", Namespace="http://graphml.graphdrawing.org/xmlns")]
    public enum GraphOrderType
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("free")]
        Free,
        
        [System.Xml.Serialization.XmlEnumAttribute("nodesfirst")]
        Nodesfirst,
        
        [System.Xml.Serialization.XmlEnumAttribute("adjacencylist")]
        Adjacencylist,
    }
}
