//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 1.0.0.0 using the following command:
// XmlSchemaClassGenerator.Console -o . -n http://graphml.graphdrawing.org/xmlns=GraphML -n http://www.w3.org/1999/xlink=XLink -n http://www.yworks.com/xml/graphml=YEd --nu --sf --csm=Public --ct=System.Array --dc .\_XSD\ygraphml.xsd
namespace GraphML
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("key.type.type", Namespace="http://graphml.graphdrawing.org/xmlns")]
    public enum KeyTypeType
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("boolean")]
        Boolean,
        
        [System.Xml.Serialization.XmlEnumAttribute("int")]
        Int,
        
        [System.Xml.Serialization.XmlEnumAttribute("long")]
        Long,
        
        [System.Xml.Serialization.XmlEnumAttribute("float")]
        Float,
        
        [System.Xml.Serialization.XmlEnumAttribute("double")]
        Double,
        
        [System.Xml.Serialization.XmlEnumAttribute("string")]
        String,
        
        [System.Xml.Serialization.XmlEnumAttribute("complex")]
        Complex,
    }
}
