//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 1.0.0.0 using the following command:
// XmlSchemaClassGenerator.Console -o . -n http://graphml.graphdrawing.org/xmlns=GraphML -n http://www.w3.org/1999/xlink=XLink -n http://www.yworks.com/xml/graphml=YEd --nu --sf --csm=Public --ct=System.Array --dc .\_XSD\ygraphml.xsd
namespace GraphML
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("data-extension.type", Namespace="http://graphml.graphdrawing.org/xmlns")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("data-extension.type", Namespace="http://graphml.graphdrawing.org/xmlns")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GraphML.DataType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GraphML.DefaultType))]
    public partial class Data_ExtensionType : GraphML.Data_ExtensionType
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Xml.XmlElement[] any;
        
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return any;
            }
            set
            {
                any = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AnySpecified
        {
            get
            {
                return ((this.Any != null) 
                            && (this.Any.Length != 0));
            }
        }
        
        public Data_ExtensionType()
        {
            this.any = System.Array.Empty<System.Xml.XmlElement>();
        }
    }
}
