//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 1.0.0.0 using the following command:
// XmlSchemaClassGenerator.Console -o . -n http://graphml.graphdrawing.org/xmlns=GraphML -n http://www.w3.org/1999/xlink=XLink -n http://www.yworks.com/xml/graphml=YEd --nu --sf --csm=Public --ct=System.Array --dc .\_XSD\ygraphml.xsd
namespace GraphML
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("node.type", Namespace="http://graphml.graphdrawing.org/xmlns")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("node", Namespace="http://graphml.graphdrawing.org/xmlns")]
    public partial class NodeType : INodeExtraAttrib, GraphML.INodeExtraAttrib
    {
        
        [System.Xml.Serialization.XmlElementAttribute("desc")]
        public string Desc { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private DataType[] data;
        
        [System.Xml.Serialization.XmlElementAttribute("data")]
        public DataType[] Data
        {
            get
            {
                return data;
            }
            set
            {
                data = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DataSpecified
        {
            get
            {
                return ((this.Data != null) 
                            && (this.Data.Length != 0));
            }
        }
        
        public NodeType()
        {
            this.data = System.Array.Empty<DataType>();
            this.port = System.Array.Empty<PortType>();
            this.graph = System.Array.Empty<GraphType>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private PortType[] port;
        
        [System.Xml.Serialization.XmlElementAttribute("port")]
        public PortType[] Port
        {
            get
            {
                return port;
            }
            set
            {
                port = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PortSpecified
        {
            get
            {
                return ((this.Port != null) 
                            && (this.Port.Length != 0));
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private GraphType[] graph;
        
        [System.Xml.Serialization.XmlElementAttribute("graph")]
        public GraphType[] Graph
        {
            get
            {
                return graph;
            }
            set
            {
                graph = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GraphSpecified
        {
            get
            {
                return ((this.Graph != null) 
                            && (this.Graph.Length != 0));
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("locator")]
        public LocatorType Locator { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("yfiles.foldertype")]
        public GraphML.YfilesFoldertypeType YfilesFoldertype { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool YfilesFoldertypeSpecified { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("parse.indegree")]
        public string ParseIndegree { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("parse.outdegree")]
        public string ParseOutdegree { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("id")]
        public string Id { get; set; }
    }
}
