//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 1.0.0.0 using the following command:
// XmlSchemaClassGenerator.Console -o . -n http://graphml.graphdrawing.org/xmlns=GraphML -n http://www.w3.org/1999/xlink=XLink -n http://www.yworks.com/xml/graphml=YEd --nu --sf --csm=Public --ct=System.Array --dc .\_XSD\ygraphml.xsd
namespace YEd
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("EdgeLabel.type", Namespace="http://www.yworks.com/xml/graphml")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EdgeLabelType : LabelType
    {
        
        [System.Xml.Serialization.XmlAttributeAttribute("modelName")]
        public EdgeLabelModelType ModelName { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ModelNameSpecified { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("modelPosition")]
        public EdgeLabelPositionType ModelPosition { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ModelPositionSpecified { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("preferredPlacement")]
        public PreferredPlacementType PreferredPlacement { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PreferredPlacementSpecified { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("distance")]
        public double Distance { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DistanceSpecified { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("ratio")]
        public double Ratio { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RatioSpecified { get; set; }
    }
}
