//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 1.0.0.0 using the following command:
// XmlSchemaClassGenerator.Console -o . -n http://graphml.graphdrawing.org/xmlns=GraphML -n http://www.w3.org/1999/xlink=XLink -n http://www.yworks.com/xml/graphml=YEd --nu --sf --csm=Public --ct=System.Array --dc .\_XSD\ygraphml.xsd
namespace YEd
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("GenericGroupNodeTypeState", Namespace="http://www.yworks.com/xml/graphml", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GenericGroupNodeTypeState
    {
        
        [System.Xml.Serialization.XmlAttributeAttribute("closed")]
        public bool Closed { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ClosedSpecified { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("autoResize")]
        public bool AutoResize { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AutoResizeSpecified { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("closedHeight")]
        public double ClosedHeight { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ClosedHeightSpecified { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("closedWidth")]
        public double ClosedWidth { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ClosedWidthSpecified { get; set; }
    }
}
