//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 1.0.0.0 using the following command:
// XmlSchemaClassGenerator.Console -o . -n http://graphml.graphdrawing.org/xmlns=GraphML -n http://www.w3.org/1999/xlink=XLink -n http://www.yworks.com/xml/graphml=YEd --nu --sf --csm=Public --ct=System.Array --dc .\_XSD\ygraphml.xsd
namespace YEd
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("NodeLabel.type", Namespace="http://www.yworks.com/xml/graphml")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NodeLabelType : LabelType
    {
        
        [System.Xml.Serialization.XmlAttributeAttribute("modelName")]
        public NodeLabelModelType ModelName { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ModelNameSpecified { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("modelPosition")]
        public NodeLabelPositionType ModelPosition { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ModelPositionSpecified { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("autoSizePolicy")]
        public AutoSizePolicyType AutoSizePolicy { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AutoSizePolicySpecified { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("borderDistance")]
        public double BorderDistance { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BorderDistanceSpecified { get; set; }
    }
}
