//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 1.0.0.0 using the following command:
// XmlSchemaClassGenerator.Console -o . -n http://graphml.graphdrawing.org/xmlns=GraphML -n http://www.w3.org/1999/xlink=XLink -n http://www.yworks.com/xml/graphml=YEd --nu --sf --csm=Public --ct=System.Array --dc .\_XSD\ygraphml.xsd
namespace YEd
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("Node.type", Namespace="http://www.yworks.com/xml/graphml")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GenericGroupNodeType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GenericNodeType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GroupNodeType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ImageNodeType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ShapeNodeType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TableNodeType))]
    public partial class NodeType
    {
        
        [System.Xml.Serialization.XmlElementAttribute("Geometry")]
        public GeometryType Geometry { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("Fill")]
        public NodeTypeFill Fill { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("BorderStyle")]
        public LineStyleType BorderStyle { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private NodeLabelType[] nodeLabel;
        
        [System.Xml.Serialization.XmlElementAttribute("NodeLabel")]
        public NodeLabelType[] NodeLabel
        {
            get
            {
                return nodeLabel;
            }
            set
            {
                nodeLabel = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NodeLabelSpecified
        {
            get
            {
                return ((this.NodeLabel != null) 
                    && (this.NodeLabel.Length != 0));
            }
        }
        
        public NodeType()
        {
            this.nodeLabel = System.Array.Empty<NodeLabelType>();
            this.nodePorts = System.Array.Empty<NodePortType>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private NodePortType[] nodePorts;
        
        [System.Xml.Serialization.XmlArrayAttribute("NodePorts")]
        [System.Xml.Serialization.XmlArrayItemAttribute("NodePort", Namespace="http://www.yworks.com/xml/graphml")]
        public NodePortType[] NodePorts
        {
            get
            {
                return nodePorts;
            }
            set
            {
                nodePorts = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NodePortsSpecified
        {
            get
            {
                return ((this.NodePorts != null) 
                            && (this.NodePorts.Length != 0));
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute("selected")]
        public bool Selected { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SelectedSpecified { get; set; }
    }
}
