//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 1.0.0.0 using the following command:
// XmlSchemaClassGenerator.Console -o . -n http://graphml.graphdrawing.org/xmlns=GraphML -n http://www.w3.org/1999/xlink=XLink -n http://www.yworks.com/xml/graphml=YEd --nu --sf --csm=Public --ct=System.Array --dc .\_XSD\ygraphml.xsd
namespace YEd
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("nodeLabelPosition.type", Namespace="http://www.yworks.com/xml/graphml")]
    public enum NodeLabelPositionType
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("n")]
        N,
        
        [System.Xml.Serialization.XmlEnumAttribute("nw")]
        Nw,
        
        [System.Xml.Serialization.XmlEnumAttribute("ne")]
        Ne,
        
        [System.Xml.Serialization.XmlEnumAttribute("w")]
        W,
        
        [System.Xml.Serialization.XmlEnumAttribute("e")]
        E,
        
        [System.Xml.Serialization.XmlEnumAttribute("sw")]
        Sw,
        
        [System.Xml.Serialization.XmlEnumAttribute("s")]
        S,
        
        [System.Xml.Serialization.XmlEnumAttribute("se")]
        Se,
        
        [System.Xml.Serialization.XmlEnumAttribute("c")]
        C,
        
        [System.Xml.Serialization.XmlEnumAttribute("tl")]
        Tl,
        
        [System.Xml.Serialization.XmlEnumAttribute("t")]
        T,
        
        [System.Xml.Serialization.XmlEnumAttribute("tr")]
        Tr,
        
        [System.Xml.Serialization.XmlEnumAttribute("r")]
        R,
        
        [System.Xml.Serialization.XmlEnumAttribute("l")]
        L,
        
        [System.Xml.Serialization.XmlEnumAttribute("bl")]
        Bl,
        
        [System.Xml.Serialization.XmlEnumAttribute("b")]
        B,
        
        [System.Xml.Serialization.XmlEnumAttribute("br")]
        Br,
        
        [System.Xml.Serialization.XmlEnumAttribute("anywhere")]
        Anywhere,
    }
}
