//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 1.0.0.0 using the following command:
// XmlSchemaClassGenerator.Console -o . -n http://graphml.graphdrawing.org/xmlns=GraphML -n http://www.w3.org/1999/xlink=XLink -n http://www.yworks.com/xml/graphml=YEd --nu --sf --csm=Public --ct=System.Array --dc .\_XSD\ygraphml.xsd
namespace YEd
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("Path.type", Namespace="http://www.yworks.com/xml/graphml")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PathType
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private PathTypePoint[] point;
        
        [System.Xml.Serialization.XmlElementAttribute("Point")]
        public PathTypePoint[] Point
        {
            get
            {
                return point;
            }
            set
            {
                point = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PointSpecified
        {
            get
            {
                return ((this.Point != null) 
                            && (this.Point.Length != 0));
            }
        }
        
        public PathType()
        {
            this.point = System.Array.Empty<PathTypePoint>();
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute("reversedPathRendering")]
        public bool ReversedPathRendering { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReversedPathRenderingSpecified { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("sx")]
        public double Sx { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SxSpecified { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("sy")]
        public double Sy { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SySpecified { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("tx")]
        public double Tx { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TxSpecified { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("ty")]
        public double Ty { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TySpecified { get; set; }
    }
}
