//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 1.0.0.0 using the following command:
// XmlSchemaClassGenerator.Console -o . -n http://graphml.graphdrawing.org/xmlns=GraphML -n http://www.w3.org/1999/xlink=XLink -n http://www.yworks.com/xml/graphml=YEd --nu --sf --csm=Public --ct=System.Array --dc .\_XSD\ygraphml.xsd
namespace YEd
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("PortLabelModelParameter.position.type", Namespace="http://www.yworks.com/xml/graphml")]
    public enum PortLabelModelParameterPositionType
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("north")]
        North,
        
        [System.Xml.Serialization.XmlEnumAttribute("south")]
        South,
        
        [System.Xml.Serialization.XmlEnumAttribute("east")]
        East,
        
        [System.Xml.Serialization.XmlEnumAttribute("west")]
        West,
        
        [System.Xml.Serialization.XmlEnumAttribute("center")]
        Center,
    }
}
