//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 1.0.0.0 using the following command:
// XmlSchemaClassGenerator.Console -o . -n http://graphml.graphdrawing.org/xmlns=GraphML -n http://www.w3.org/1999/xlink=XLink -n http://www.yworks.com/xml/graphml=YEd --nu --sf --csm=Public --ct=System.Array --dc .\_XSD\ygraphml.xsd
namespace YEd
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("Postprocessors.type", Namespace="http://www.yworks.com/xml/graphml")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("Postprocessors", Namespace="http://www.yworks.com/xml/graphml")]
    public partial class PostprocessorsType
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private ProcessorType[] processor;
        
        [System.Xml.Serialization.XmlElementAttribute("Processor")]
        public ProcessorType[] Processor
        {
            get
            {
                return processor;
            }
            set
            {
                processor = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ProcessorSpecified
        {
            get
            {
                return ((this.Processor != null) 
                            && (this.Processor.Length != 0));
            }
        }
        
        public PostprocessorsType()
        {
            this.processor = System.Array.Empty<ProcessorType>();
        }
    }
}
