//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 1.0.0.0 using the following command:
// XmlSchemaClassGenerator.Console -o . -n http://graphml.graphdrawing.org/xmlns=GraphML -n http://www.w3.org/1999/xlink=XLink -n http://www.yworks.com/xml/graphml=YEd --nu --sf --csm=Public --ct=System.Array --dc .\_XSD\ygraphml.xsd
namespace YEd
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("preferredPlacement.type", Namespace="http://www.yworks.com/xml/graphml")]
    public enum PreferredPlacementType
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("target_right")]
        Target_Right,
        
        [System.Xml.Serialization.XmlEnumAttribute("target")]
        Target,
        
        [System.Xml.Serialization.XmlEnumAttribute("target_left")]
        Target_Left,
        
        [System.Xml.Serialization.XmlEnumAttribute("target_on_edge")]
        Target_On_Edge,
        
        [System.Xml.Serialization.XmlEnumAttribute("source_right")]
        Source_Right,
        
        [System.Xml.Serialization.XmlEnumAttribute("source")]
        Source,
        
        [System.Xml.Serialization.XmlEnumAttribute("source_left")]
        Source_Left,
        
        [System.Xml.Serialization.XmlEnumAttribute("source_on_edge")]
        Source_On_Edge,
        
        [System.Xml.Serialization.XmlEnumAttribute("center_right")]
        Center_Right,
        
        [System.Xml.Serialization.XmlEnumAttribute("center")]
        Center,
        
        [System.Xml.Serialization.XmlEnumAttribute("center_left")]
        Center_Left,
        
        [System.Xml.Serialization.XmlEnumAttribute("center_on_edge")]
        Center_On_Edge,
        
        [System.Xml.Serialization.XmlEnumAttribute("anywhere")]
        Anywhere,
        
        [System.Xml.Serialization.XmlEnumAttribute("on_edge")]
        On_Edge,
        
        [System.Xml.Serialization.XmlEnumAttribute("left")]
        Left,
        
        [System.Xml.Serialization.XmlEnumAttribute("right")]
        Right,
    }
}
