//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 1.0.0.0 using the following command:
// XmlSchemaClassGenerator.Console -o . -n http://graphml.graphdrawing.org/xmlns=GraphML -n http://www.w3.org/1999/xlink=XLink -n http://www.yworks.com/xml/graphml=YEd --nu --sf --csm=Public --ct=System.Array --dc .\_XSD\ygraphml.xsd
namespace YEd
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ResourceBlock.type", Namespace="http://www.yworks.com/xml/graphml")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("Resources", Namespace="http://www.yworks.com/xml/graphml")]
    public partial class ResourceBlockType
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private ResourceType[] resource;
        
        [System.Xml.Serialization.XmlElementAttribute("Resource")]
        public ResourceType[] Resource
        {
            get
            {
                return resource;
            }
            set
            {
                resource = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ResourceSpecified
        {
            get
            {
                return ((this.Resource != null) 
                            && (this.Resource.Length != 0));
            }
        }
        
        public ResourceBlockType()
        {
            this.resource = System.Array.Empty<ResourceType>();
        }
    }
}
