//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 1.0.0.0 using the following command:
// XmlSchemaClassGenerator.Console -o . -n http://graphml.graphdrawing.org/xmlns=GraphML -n http://www.w3.org/1999/xlink=XLink -n http://www.yworks.com/xml/graphml=YEd --nu --sf --csm=Public --ct=System.Array --dc .\_XSD\ygraphml.xsd
namespace YEd
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TableTypeColumns", Namespace="http://www.yworks.com/xml/graphml", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TableTypeColumns
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private TableColumnType[] column;
        
        [System.Xml.Serialization.XmlElementAttribute("Column")]
        public TableColumnType[] Column
        {
            get
            {
                return column;
            }
            set
            {
                column = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ColumnSpecified
        {
            get
            {
                return ((this.Column != null) 
                            && (this.Column.Length != 0));
            }
        }
        
        public TableTypeColumns()
        {
            this.column = System.Array.Empty<TableColumnType>();
        }
    }
}
